version: "3.3"

services: 
    trendcalc-eureka-service:
        image: docker-eureka
        ports: 
            - "8761:8761"
    spring-security:
        image: docker-spring-security
        ports: 
            - "9000:9000"
        depends_on:
            - trendcalc-db
    trendcalc-db:
        image: mysql
        ports: 
            - "3308:3307"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mydatabase
            - MYSQL_TCP_PORT=3307
        volumes:
            - my-vol:/var/lib/mysql
    trendcalc-service:
        image: docker-trendcalc-api
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://trendcalc-eureka-service:8761/eureka
            - SPRING_DATASOURCE_URL=jdbc:mysql://trendcalc-db:3307/mydatabase?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
            # - DB_UPSTREAM=
            #     -http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000
        ports:
            - "8082:8082"      
        depends_on:
            - trendcalc-eureka-service
            - trendcalc-db
            - spring-security
        volumes:
            - my-files:/home/files
    trendcalc-zuul-service:
        image: docker-zuul
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://trendcalc-eureka-service:8761/eureka
        ports: 
            - "3333:3333"
        depends_on:
            - trendcalc-eureka-service
            - trendcalc-service     
    trendcalc-ui-service:
        image: angular-docker-image
        ports:
            - "4200:4200"
        depends_on:
            - trendcalc-zuul-service
            - spring-security
volumes:
    my-vol:
    my-files:

